---
- name: Deploy nginx on EC2
  hosts: frontend

  roles:
    - role: nginx


#Deu errado porque o diretorio www drive na task de copiar o index.html nao existe, ou cria ou ve um jeito melhor de copiar o arquivo
